import{RESPONSE_PLANS,FACT_IDS,UTTERANCE_VARIANTS}from"./catalog.js";import type{ConversationState,ResponsePlan,UserTurnEnvelope}from"./contracts.js";
const byId=new Map(RESPONSE_PLANS.map(p=>[p.id,p]));export const initialState=():ConversationState=>({tension:"TENSE",openness:"GUARDED",resolutionStage:"ISSUE_RAISED",revealedFacts:[],lastPlanId:"",variantHistory:[],turn:0});
export function planPreconditions(plan:ResponsePlan,state:ConversationState,envelope:UserTurnEnvelope){if(plan.forbiddenStages.includes(state.resolutionStage))return false;if(!plan.allowedIntents.includes(envelope.intent))return false;if(plan.requiredFacts.some(f=>!FACT_IDS.has(f)))return false;if(plan.requiredRevealedFacts.some(f=>!state.revealedFacts.includes(f)))return false;return true;}
export function candidatePlans(state:ConversationState,envelope:UserTurnEnvelope):ResponsePlan[]{const started=performance.now();void started;let plans=RESPONSE_PLANS.filter(p=>planPreconditions(p,state,envelope));if(!plans.length){const fallback=byId.get("PLAN_ASK_CLARIFICATION")!;if(state.resolutionStage!=="ENDED")plans=[fallback];}return plans;}
const step=<T>(value:T,order:T[],direction:number)=>order[Math.max(0,Math.min(order.length-1,order.indexOf(value)+direction))]!;
export function applyPlan(state:ConversationState,plan:ResponsePlan):ConversationState{if(state.resolutionStage==="ENDED")throw new Error("TRANSITION_FROM_ENDED");const tensionOrder:ConversationState["tension"][]=["CALM","TENSE","HIGH"],opennessOrder:ConversationState["openness"][]=["CLOSED","GUARDED","OPEN"];const tension=step(state.tension,tensionOrder,plan.effects.tension==="INCREASE"?1:plan.effects.tension==="DECREASE"?-1:0),openness=step(state.openness,opennessOrder,plan.effects.openness==="OPEN_MORE"?1:plan.effects.openness==="CLOSE_MORE"?-1:0),resolutionStage=plan.effects.stage==="HOLD"?state.resolutionStage:plan.effects.stage,revealedFacts=[...new Set([...state.revealedFacts,...plan.manifest.reveals])].sort();return{...state,tension,openness,resolutionStage,revealedFacts,lastPlanId:plan.id,turn:state.turn+1};}
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export function selectVariant(plan:ResponsePlan,locale:"en-US"|"pt-BR",state:ConversationState,seed:string){const all=UTTERANCE_VARIANTS.filter(v=>v.familyId===plan.utteranceFamilyId&&v.locale===locale),recent=new Set(state.variantHistory.slice(-3)),pool=all.filter(v=>!recent.has(v.id));const choices=pool.length?pool:all;const chosen=choices[hash(seed)%choices.length]!;return chosen;}
export function planById(id:string){return byId.get(id);}export function variantsForPlan(id:string){const p=byId.get(id);return p?UTTERANCE_VARIANTS.filter(v=>v.familyId===p.utteranceFamilyId):[];}
