import{GoogleGenAI,ThinkingLevel}from"@google/genai";import{buildSelectorInput,classifyHttp200,SELECTOR_SYSTEM_PROMPT_V056,selectorSchema}from"../frozen.js";import type{SelectorCase}from"../frozen.js";import type{Locale,ProviderAttempt,SelectorPort,SelectorResult}from"../domain/contracts.js";import{ConcurrencyLimiter}from"../resilience/concurrency-limiter.js";
type Usage={inputTokens:number;outputTokens:number;thinkingTokens:number;totalTokens:number};
export type RawSelectorResponse={rawText:string;finishReason:string|null;usage:Usage};
export interface RawSelectorTransport{call(input:{case:SelectorCase;timeoutMs:number}):Promise<RawSelectorResponse>;}
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:0,zero=():Usage=>({inputTokens:0,outputTokens:0,thinkingTokens:0,totalTokens:0}),add=(a:Usage,b:Usage):Usage=>({inputTokens:a.inputTokens+b.inputTokens,outputTokens:a.outputTokens+b.outputTokens,thinkingTokens:a.thinkingTokens+b.thinkingTokens,totalTokens:a.totalTokens+b.totalTokens});
const statusOf=(error:unknown)=>{const e=error as any;for(const v of[e?.status,e?.code])if(typeof v==="number")return v;const m=String(e?.message??error).match(/\b(4\d\d|5\d\d)\b/);return m?Number(m[1]):null;};
function transportKind(error:unknown):ProviderAttempt["kind"]|null{const status=statusOf(error),message=String((error as any)?.message??error);return[429,499,500,503,504].includes(status??0)||/ECONNRESET|fetch failed|timeout|timed out|deadline|capacity|abort/i.test(message)?"TRANSPORT_FAILURE":null;}
export class VertexRawSelectorTransport implements RawSelectorTransport{readonly #client:GoogleGenAI;constructor(project:string,readonly location="global",readonly limiter=new ConcurrencyLimiter(2,8)){this.#client=new GoogleGenAI({vertexai:true,project,location,httpOptions:{baseUrl:"https://aiplatform.googleapis.com",apiVersion:"v1"}});}async call(input:{case:SelectorCase;timeoutMs:number}){return this.limiter.run(async()=>{const response=await this.#client.models.generateContent({model:"gemini-3.7-flash",contents:buildSelectorInput([input.case]),config:{systemInstruction:SELECTOR_SYSTEM_PROMPT_V056,thinkingConfig:{thinkingLevel:ThinkingLevel.LOW},maxOutputTokens:512,responseMimeType:"application/json",responseJsonSchema:selectorSchema(input.case.candidatePlanIds,[input.case.id]),httpOptions:{timeout:input.timeoutMs,retryOptions:{attempts:1}}}}),u=(response as any).usageMetadata??{};return{rawText:response.text??"",finishReason:String((response as any)?.candidates?.[0]?.finishReason??"")||null,usage:{inputTokens:num(u.promptTokenCount),outputTokens:num(u.candidatesTokenCount),thinkingTokens:num(u.thoughtsTokenCount),totalTokens:num(u.totalTokenCount)}};});}}
export class VertexSelectorClient implements SelectorPort{constructor(readonly transport:RawSelectorTransport,private readonly now=()=>performance.now(),private readonly sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms)),readonly minAttemptBudgetMs=1500){}async select(input:{requestId:string;userTurn:string;resolvedPrimaryIntent:string;state:any;recentContext:string[];candidates:any[];locale:Locale;deadlineMs:number}):Promise<SelectorResult>{const started=this.now(),deadline=started+input.deadlineMs,attempts:ProviderAttempt[]=[];let usage=zero(),transportRetries=0,structuralRetries=0;const item:SelectorCase={id:input.requestId,locale:input.locale,category:"BACKEND_RUNTIME",difficulty:"MEDIUM",userIntent:input.resolvedPrimaryIntent,userTurn:input.userTurn,state:input.state,recentContext:input.recentContext,candidatePlanIds:input.candidates.map(x=>x.id),acceptablePlanIds:input.candidates.map(x=>x.id),preferredPlanIds:[],intentLock:null,paraphraseGroupId:null,forkPairId:null,forkKind:null};
    for(let structural=1;structural<=2;structural++){for(let transport=1;transport<=3;transport++){const remaining=Math.floor(deadline-this.now());if(remaining<this.minAttemptBudgetMs)throw Object.assign(new Error("SELECTOR_GLOBAL_DEADLINE"),{attempts,transportRetries,structuralRetries});const t=this.now();try{const response=await this.transport.call({case:item,timeoutMs:remaining}),latency=Math.round(this.now()-t);usage=add(usage,response.usage);let parsed:unknown;try{parsed=response.rawText.trim()?JSON.parse(response.rawText):undefined}catch{parsed=undefined;}const checked=classifyHttp200(response.rawText,response.finishReason,parsed,item.candidatePlanIds,item.id);if(checked.decision){attempts.push({attempt:attempts.length+1,kind:"SUCCESS",httpStatus:200,latencyMs:latency,finishReason:response.finishReason});return{planId:checked.decision.planId,confidence:checked.decision.confidence,latencyMs:Math.round(this.now()-started),transportRetries,structuralRetries,attempts,usage};}const kind=(checked.failureClass??"UNKNOWN_STRUCTURAL_FAILURE") as ProviderAttempt["kind"];attempts.push({attempt:attempts.length+1,kind,httpStatus:200,latencyMs:latency,finishReason:response.finishReason});if(structural===2)throw Object.assign(new Error(kind),{attempts,transportRetries,structuralRetries});structuralRetries++;break;}catch(error){if((error as any)?.attempts)throw error;const latency=Math.round(this.now()-t),kind=transportKind(error);if(!kind)throw error;attempts.push({attempt:attempts.length+1,kind,httpStatus:statusOf(error),latencyMs:latency,finishReason:null});const remainingAfter=deadline-this.now();if(transport===3||remainingAfter<this.minAttemptBudgetMs)throw Object.assign(new Error("SELECTOR_TRANSPORT_FAILURE"),{attempts,transportRetries,structuralRetries});transportRetries++;const backoff=Math.min(500*2**(transport-1),Math.max(0,remainingAfter-this.minAttemptBudgetMs));if(backoff)await this.sleep(backoff);}}
    }throw Object.assign(new Error("SELECTOR_UNKNOWN_STRUCTURAL_FAILURE"),{attempts,transportRetries,structuralRetries});}}

