import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { FAMILY_BY_INTENT } from "./contracts.js";
const blind=JSON.parse(await readFile(resolve("results/v052/blind-results.json"),"utf8")),dataset=JSON.parse(await readFile(resolve("results/v052/blind-dataset.json"),"utf8")),freeze=JSON.parse(await readFile(resolve("results/v052/router-freeze.json"),"utf8")),datasetFreeze=JSON.parse(await readFile(resolve("results/v052/blind-freeze.json"),"utf8")),calibration=JSON.parse(await readFile(resolve("results/v052/existing-pilot-results.json"),"utf8")),stability=JSON.parse(await readFile(resolve("results/v052/stability-results.json"),"utf8")),ledger=JSON.parse(await readFile(resolve("results/v052/api-call-ledger.json"),"utf8"));
const byId=new Map(blind.records.map((x:any)=>[x.id,x])),groups=new Map<string,any[]>();for(const c of dataset.cases){const values=groups.get(c.groupId)??[];values.push(byId.get(c.id));groups.set(c.groupId,values)}
const cleanGroups=[...groups.values()].filter(v=>v.every((x:any)=>x&&!x.labelDrift&&!x.schemaFailure)),familyStable=cleanGroups.filter(v=>new Set(v.map((x:any)=>FAMILY_BY_INTENT[x.predictedPrimary as keyof typeof FAMILY_BY_INTENT])).size===1).length,exactStable=cleanGroups.filter(v=>new Set(v.map((x:any)=>x.predictedPrimary)).size===1).length;
const claimCases=blind.records.filter((x:any)=>!x.labelDrift&&x.claimExpected>0),noClaim=blind.records.filter((x:any)=>!x.labelDrift&&x.claimExpected===0);
const stageCounts=Object.fromEntries(["dataset_generation","router_calibration","router_blind","router_stability","qa"].map(s=>[s,ledger.entries.filter((x:any)=>x.stage===s).length])),transportRetryCalls=ledger.entries.filter((x:any)=>x.transportRetry>0).length;
const resultDirs=["existing-pilot-batches","blind-generation-batches","rejected-ambiguous-v1","blind-router-batches","stability-batches"];
let cost=0,inputTokens=0,outputTokens=0,thinkingTokens=0;for(const name of resultDirs){const path=resolve("results/v052",name);for(const file of(await readdir(path)).filter(x=>x.endsWith(".json"))){const x=JSON.parse(await readFile(resolve(path,file),"utf8"));cost+=x.estimatedCostUsd??0;inputTokens+=x.usage?.inputTokens??0;outputTokens+=x.usage?.outputTokens??0;thinkingTokens+=x.usage?.thinkingTokens??0}}
const confusions=Object.entries(blind.records.filter((x:any)=>!x.labelDrift&&!x.acceptableIntent).reduce((a:any,x:any)=>{const k=`${x.expectedPrimary}->${x.predictedPrimary??"SCHEMA_FAILURE"}`;a[k]=(a[k]??0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,20).map(([pair,count])=>({pair,count}));
const payload={schemaVersion:"v052-final-metrics-1",generatedAt:new Date().toISOString(),status:"YELLOW",recommendation:"ONE_SMALL_ROUTER_TUNING_PASS",readyForSelectorStressTest:false,model:{name:"gemini-3.7-flash",thinking:"low",batchSize:5},calls:{ledger:ledger.count,directDiagnostics:3,total:ledger.count+3,byStage:stageCounts,transportRetryCalls,qa:0},cost:{totalUsd:cost,inputTokens,outputTokens,thinkingTokens,costPerRoutingUsd:blind.summary.costPerRoutingUsd,sixTurnRoutingUsd:blind.summary.costPerRoutingUsd*6,conversations100:blind.summary.costPerRoutingUsd*6*100,conversations1000:blind.summary.costPerRoutingUsd*6*1000,conversations10000:blind.summary.costPerRoutingUsd*6*10000,pricingDate:"2026-08-26",pricing:{inputPerMillionUsd:.75,outputPerMillionUsd:3.75}},freeze,dataset:{...datasetFreeze,labelDriftRate:.016,manualReview:500},calibration:calibration.summary,blind:blind.summary,claims:{cases:claimCases.length,recall:claimCases.filter((x:any)=>x.claimDetected>0).length/claimCases.length,typeAccuracy:claimCases.filter((x:any)=>x.claimTypeCorrect).length/claimCases.length,sourceSpanValidity:blind.summary.claimSourceSpanValidity,falsePositiveRate:noClaim.filter((x:any)=>x.claimDetected>0).length/noClaim.length,grounding:blind.grounding},paraphrase:{groups:cleanGroups.length,familyStable, familyStabilityRate:familyStable/cleanGroups.length,exactStable,exactStabilityRate:exactStable/cleanGroups.length},stability,confusions,verdicts:{ptBR:"Candidate coverage solved (99.25%), but ambiguity calibration and claim over-extraction remain below the Router gate.",enUS:"Candidate coverage solved (99.44%), with the same cross-locale ambiguity/claim calibration weakness.",architecture:"Semantic Router solved open-language-to-safe-candidate coverage, but not calibrated ambiguity or stable finite intent classification at GREEN quality.",graph:"The unchanged 25-plan graph remains sufficient; true graph gaps were 0%."},mainFailureClusters:["AMBIGUOUS routed as ASK_CAPABILITY or REQUEST_COMPLETION", "Claims over-extracted from non-assertive language", "UNKNOWN/OTHER claim types sometimes mapped to grounded scenario facts", "Same-input instability concentrated in AMBIGUOUS and UNCLEAR"]};await writeFile(resolve("results/v052/final-metrics.json"),`${JSON.stringify(payload,null,2)}\n`);process.stdout.write(`${JSON.stringify(payload,null,2)}\n`);
