import type { RouterIntent } from "./contracts.js";

export const INTENT_DEFINITIONS: Record<RouterIntent, string> = {
  ASK_STATUS: "asks what work or which slides remain unfinished",
  ASK_CAUSE: "asks what happened, what obstacle existed, or why progress is delayed without asserting the answer",
  ASK_SCHEDULE: "asks whether or how Alex's internship schedule changed",
  ASK_LOST_TIME: "asks how much work time or how many evenings Alex lost",
  ASK_CAPABILITY: "asks what Alex can realistically finish or deliver",
  REQUEST_COMPLETION: "asks or directs Alex to finish or send project work; requested action, not capability question",
  ACCUSE_GENERALIZATION: "broad always/never judgment about Alex's effort, reliability, or character",
  THREAT_ESCALATION: "threatens professor escalation, public blame, removal, or another consequence",
  PROPOSE_COLLABORATION: "offers help or proposes working together on the remaining project work",
  EXPRESS_FRUSTRATION: "expresses stress, fatigue, disappointment, or frustration without a stronger primary move",
  PASSIVE_AGGRESSIVE: "uses sarcasm, martyrdom, or indirect blame such as implying the user must do Alex's work again",
  APOLOGIZE: "apologizes or admits the user's tone or behavior was unfair",
  CHANGE_TOPIC: "pauses, dismisses, ends, or changes away from the project conversation",
  ACKNOWLEDGE_CONTEXT: "acknowledges Alex's perspective or attempts a constructive conversational reset",
  ACCEPT_PLAN: "accepts a plan or division of work already proposed",
  ASSERT_CLAIM: "asserts a potentially checkable fact about deadline, prior history, Alex's personal life, schedule, or project state",
  META_PROMPT_ATTACK: "asks for system instructions, role change, hidden facts, free text, or a forced plan ID",
  OUT_OF_SCOPE: "content genuinely unrelated to this teammate/project conversation",
  AMBIGUOUS: "two materially different primary interpretations are genuinely plausible",
  UNCLEAR: "meaning is too incomplete or incoherent to identify a useful intent",
};

export const ROUTER_CONTRASTS = [
  "ASK_CAPABILITY asks what is possible; REQUEST_COMPLETION asks Alex to do it.",
  "ASK_CAUSE asks why/what got in the way; ASK_STATUS asks what remains unfinished.",
  "EXPRESS_FRUSTRATION states emotion; ACCUSE_GENERALIZATION judges Alex with a broad pattern; PASSIVE_AGGRESSIVE conveys blame indirectly or sarcastically.",
  "PROPOSE_COLLABORATION offers joint action; ACKNOWLEDGE_CONTEXT validates perspective or resets the tone.",
  "ASSERT_CLAIM reports what the user asserted and never means that the claim is true.",
  "A polite modal request such as 'Could you finish it?' is REQUEST_COMPLETION, not ASK_CAPABILITY, unless it genuinely asks whether finishing is possible.",
];

export const OLD_TO_ROUTER: Record<string, RouterIntent> = {
  ASK_CAUSE: "ASK_CAUSE",
  ASK_SCHEDULE: "ASK_SCHEDULE",
  ASK_LOST_TIME: "ASK_LOST_TIME",
  ASK_CAPABILITY: "ASK_CAPABILITY",
  REQUEST_COMPLETION: "REQUEST_COMPLETION",
  ACCUSE_GENERALIZATION: "ACCUSE_GENERALIZATION",
  THREAT_ESCALATION: "THREAT_ESCALATION",
  PROPOSE_COLLABORATION: "PROPOSE_COLLABORATION",
  EXPRESS_FRUSTRATION: "EXPRESS_FRUSTRATION",
  PASSIVE_AGGRESSIVE: "PASSIVE_AGGRESSIVE",
  FALSE_DEADLINE_CLAIM: "ASSERT_CLAIM",
  UNKNOWN_PERSONAL_CLAIM: "ASSERT_CLAIM",
  FALSE_HISTORY_CLAIM: "ASSERT_CLAIM",
  META_PROMPT_ATTACK: "META_PROMPT_ATTACK",
  APOLOGIZE: "APOLOGIZE",
  REQUEST_CLARIFICATION: "ASK_STATUS",
  UNFAIR_SCOPE_REQUEST: "REQUEST_COMPLETION",
  CHANGE_TOPIC: "CHANGE_TOPIC",
  ACKNOWLEDGE_CONTEXT: "ACKNOWLEDGE_CONTEXT",
  ACCEPT_PLAN: "ACCEPT_PLAN",
  ASK_STATUS: "ASK_STATUS",
  AMBIGUOUS: "AMBIGUOUS",
  UNCLEAR: "UNCLEAR",
};
