import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { SelectorCase, SelectorRouteRecord } from "./contracts.js";
import { GeminiPlanSelectorV056 } from "./selector.js";

export function signature(item:SelectorCase){return item.candidatePlanIds.join("|")}
export function makeBatches(cases:SelectorCase[],size:number){const groups=new Map<string,SelectorCase[]>();for(const item of cases){const key=signature(item);const rows=groups.get(key)??[];rows.push(item);groups.set(key,rows)}const batches:SelectorCase[][]=[];for(const rows of groups.values())for(let i=0;i<rows.length;i+=size)batches.push(rows.slice(i,i+size));return batches;}
export async function runCases(input:{cases:SelectorCase[];batchSize:number;concurrency:number;prefix:string;output:string;runtime?:boolean;checkpointDir?:string}){
  const selector=new GeminiPlanSelectorV056(input.concurrency),batches=makeBatches(input.cases,input.batchSize);let cursor=0;const records:SelectorRouteRecord[]=[];let completed=0;
  if(input.checkpointDir)await mkdir(resolve(input.checkpointDir),{recursive:true});
  async function worker(){for(;;){const index=cursor++;const batch=batches[index];if(!batch)return;const checkpoint=input.checkpointDir?resolve(input.checkpointDir,`${String(index+1).padStart(5,"0")}.json`):null;let rows:SelectorRouteRecord[]|null=null;if(checkpoint)try{rows=(JSON.parse(await readFile(checkpoint,"utf8")) as {records:SelectorRouteRecord[]}).records}catch{}if(!rows){rows=await selector.selectBatch(`${input.prefix}_${String(index+1).padStart(5,"0")}`,batch,input.runtime??false);if(checkpoint)await writeFile(checkpoint,`${JSON.stringify({records:rows},null,2)}\n`);}records.push(...rows);completed+=rows.length;if(completed%100===0||completed===input.cases.length)process.stdout.write(`${input.prefix} ${completed}/${input.cases.length}\n`);}}
  await Promise.all(Array.from({length:input.concurrency},()=>worker()));records.sort((a,b)=>a.case.id.localeCompare(b.case.id));await mkdir(resolve(input.output,".."),{recursive:true});await writeFile(resolve(input.output),`${JSON.stringify({schemaVersion:"v056-route-records-1",createdAt:new Date().toISOString(),records},null,2)}\n`);return records;
}
export function summarize(records:SelectorRouteRecord[]){const n=records.length,count=(fn:(r:SelectorRouteRecord)=>boolean)=>records.filter(fn).length,sum=(fn:(r:SelectorRouteRecord)=>number)=>records.reduce((a,r)=>a+fn(r),0);return{n,acceptableHits:count(r=>r.acceptableHit),acceptableRate:count(r=>r.acceptableHit)/n,preferredEligible:count(r=>r.preferredHit!==null),preferredHits:count(r=>r.preferredHit===true),preferredRate:count(r=>r.preferredHit!==null)?count(r=>r.preferredHit===true)/count(r=>r.preferredHit!==null):null,invalidPlans:count(r=>r.invalidPlan),unsafePlans:count(r=>r.unsafePlan),fallbacks:count(r=>r.fallbackUsed),fallbackRate:count(r=>r.fallbackUsed)/n,logicalCalls:sum(r=>r.logicalCalls),httpAttempts:sum(r=>r.httpAttempts),transportRetries:sum(r=>r.transportRetries),costUsd:sum(r=>r.estimatedCostUsd),usage:{inputTokens:sum(r=>r.usage.inputTokens),outputTokens:sum(r=>r.usage.outputTokens),thinkingTokens:sum(r=>r.usage.thinkingTokens),totalTokens:sum(r=>r.usage.totalTokens)},confidence:Object.fromEntries(["HIGH","MEDIUM","LOW"].map(c=>[c,count(r=>r.decision?.confidence===c)]))};}
